version: '3.9'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-lts
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword1!
    ports:
      - "1433:1433"
